### ISSUE TITLE
CMake error on Linux

### ISSUE THREAD

**Issue by SuryamB** [projectNe10/Ne10#109]
I tried to compile Ne10 on raspberry pi 2, and I see this error, can someone please help.
Thanks
----------------------------------------------------------------------------------------------------------------
cmake -DCMAKE_TOOLCHAIN_FILE=../GNUlinux_config.cmake ..
-- Target architecture :
CMake Error at CMakeLists.txt:83 (if):
  if given arguments:
    "STREQUAL" "armv7"
  Unknown arguments specified
-- Configuring incomplete, errors occurred!

**Comment by Phillip-Wang** [comment]
Please run `export NE10_LINUX_TARGET_ARCH=armv7` before you run cmake. If the problem still exists, please let us know.

**Comment by al1970** [comment]
I tried to compile for RPi 2 but I still see the issue even with following commands:
$export NE10_LINUX_TARGET_ARCH=armv7
$cmake -DGNULINUX?PLATFORM=ON ..

I still get the same error, please help.

**Comment by hyforward** [comment]
I tried to compile for NE10 but I  see the issue even with following commands:
$export NE10_LINUX_TARGET_ARCH=armv7
$cmake -DGNULINUX?PLATFORM=ON ..


heyunfei@ubuntu:/home/ne10/projectNe10-Ne10-ee5d856/build$ export NE10_LINUX_TARGET_ARCH=armv7
heyunfei@ubuntu:/home/ne10/projectNe10-Ne10-ee5d856/build$ cmake -DGNULINUX_PLATFORM=ON ..
-- Target architecture : 
CMake Error at CMakeLists.txt:83 (if):
  if given arguments:

    "STREQUAL" "armv7"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
See also "/home/ne10/projectNe10-Ne10-ee5d856/build/CMakeFiles/CMakeOutput.log".
mail: hyf_forward@163.com

**Comment by nuborasi** [comment]
I had the same issue and had to change cmake/FunctionSwitch.cmake to add quotes around ${NE10_TARGET_ARCH} on line 29:

if("${NE10_TARGET_ARCH}" STREQUAL "armv7")

**Comment by joesavage** [comment]
The cheap fix here is to specify `NE10_LINUX_TARGET_ARCH` to `cmake` directly, like `cmake -DGNULINUX_PLATFORM=ON -DNE10_LINUX_TARGET_ARCH="armv7" ..`, as this prevents the empty string issues causing this rather opaque error. If you're using `GNUlinux_config.cmake` for cross-compiling though, you should probably **also** have the `export`! Hopefully this will get fixed at some point so that it isn't necessary to do both (and such that the build instructions actually work).

@nuborasi is quite right that `${NE10_TARGET_ARCH}` should be fixed up to `"${NE10_TARGET_ARCH}"` in a few places (not just `FunctionSwitch.cmake`), but applying this fix alone results in an empty "target architecture" variable within cmake, which isn't really supposed to happen.
