### ISSUE TITLE
NE10 - using methods

### ISSUE THREAD

**Issue by RRRZZZVVV** [projectNe10/Ne10#117]
Hello all,
- I have one question related to using some methods from NE10 library: I would like to know if it's safe to use the input, as input and destination in the same time. For instance, let's consider using the next method from NE10:

// Adds a constant scalar value to all the elements of an input array and stores the results in an //output array.
ne10_addc_float_neon (ne10_float32_t \* dst, ne10_float32_t \* src, const ne10_float32_t cst, ne10_uint32_t count);

So, it's safe to do something like this?:

ne10_addc_float_neon (SRC, SRC, VALUE, COUNT); // I used SRC as source and destination.

Can I have any kind of problems using the method this way?

Regards!

**Comment by joesavage** [comment]
As far as I know, the `ne10_addc_float_neon` and `ne10_addc_float_c` functions do indeed support in-place processing. At least, the C version looks like it does, and the NEON in-place version worked on my machine, so I'm extrapolating that it probably works fine in general.

Ideally, this kind of information would be readily available in the [documentation](http://projectne10.github.io/Ne10/doc/index.html), but it appears that this is not the case here. Further, it's extremely difficult to get a rough idea of what's going on from the code for these functions due to the [heavy](https://github.com/projectNe10/Ne10/blob/master/modules/math/NE10_addc.neon.c#L41) [use](https://github.com/projectNe10/Ne10/blob/master/common/macros.h#L44) [of](https://github.com/projectNe10/Ne10/blob/master/common/factor.h#L187) [macros](https://github.com/projectNe10/Ne10/blob/master/common/factor.h#L167) (even in this very simple function of adding a scalar value to each element of a vector!).

Though these problems might seem somewhat trivial from a technical perspective, I really think that more of an attempt should be made towards fixing them, as they significantly decrease the utility of the library by severing its usability. This is also mirrored in #98, where a simple question about how the matrix multiply functions work is nowhere near as easy as it should be to answer -- the documentation does a poor job of describing what's what, and the code is unreadable!

**Comment by joesavage** [comment]
The relevant documentation has been updated to reflect that this function can be performed in-place by 2bff9fd36b6f2c621cd83af87ebad26687cdb5b1
