### ISSUE TITLE
Ne10 DSP Performance Test - Incorrect times reported

### ISSUE THREAD

**Issue by benjmarshall** [projectNe10/Ne10#129]
All performance tests in the DSP modules use a macro 'GET_TIME' to wrap function tests in timer code. This macro uses the function 'GetTickCount()' defined in 'seatest.c' to return the time at the start and end of the test. 'GetTickCount()' uses to the standard 'gettimeofday' function available in time.h to return the current time in **microseconds**.

The code used throughout the performance tests to log to the console specify that results are reported in **milliseconds**, however they all use the returned value from 'GetTickCount' directly which is in microseconds, thus reporting all times incorrectly.

The performance tests should be modified to specify that times are reported in microseconds to resolve this.

Additionally I would suggest the function 'GetTickCount' be replaced or renamed to more clearly show that the the returned value is a time and not a number of clock ticks. This was a major source of confusion when attempting to debug why the reported times seemed to be incorrect.

**Comment by joesavage** [comment]
You are quite right that this is needlessly confusing. It looks like the name `GetTickCount` was carried over from the original [seatest](https://github.com/keithn/seatest) code, where it referred to the [Windows library function](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724408(v=vs.85).aspx) to get the number of **milliseconds** elapsed since the system started! And as for the labeling of performance measurements as bring "in ms", this is plainly wrong. I'll work up a patch to resolve these inconsistencies.
