### ISSUE TITLE
Compiling Ne10 for zynq baremetal

### ISSUE THREAD

**Issue by h-sh-h** [projectNe10/Ne10#149]
Hello
I'm trying to compile Ne10 for zynq baremetal. Following the "Building.md" instruction, I replaced xilinx-arm-eabi-gcc & others in GNUlinux_config.cmake file & then try to use cmake following the code below
    cmake -DCMAKE_TOOLCHAIN_FILE=../GNUlinux_config.cmake ..
But it gives me error like this
    arm-xilinx-eabi-gcc: error: unrecognized command line option '-rdynamic'

What should i do ?

EDIT 
I check the gcc version too ( output of cmake )
The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- The ASM compiler identification is GNU

Thanks in advance

**Comment by joesavage** [comment]
It looks like CMake adds `-rdynamic` to some subset of builds automatically, but that your toolchain doesn't support this. As far as I know we don't need this flag in the Ne10 build process, so you should be able to get rid of it from your local CMake configuration. I believe you can do this by navigating to your CMake install directory (e.g. `/usr/share/cmake-x.x`), and then removing the relevant references to the flag in the `Modules/Platform` directory.

**Comment by h-sh-h** [comment]
Hi
Thanks for reply it worked and cmake stage passed .
But when i run make i get the long list of errors which seems to be same type

invalid conversion from 'ne10_int32_t* {aka int*}' to 'const int32_t* {aka const long int*}' [-fpermissive]
#define NE10_CPLX_LOAD(PTR) vld2q_s32 ((ne10_int32_t*) (PTR))

invalid conversion from 'ne10_int32_t* {aka int*}' to 'int32_t* {aka long int*}' [-fpermissive]
vst2q_s32 ((ne10_int32_t*) (PTR), OUT);

error: invalid conversion from 'ne10_int32_t* {aka int*}' to 'const int32_t* {aka const long int*}' [-fpermissive]
#define NE10_CPLX_LOAD(PTR) vld2q_s32 ((ne10_int32_t*) (PTR))

And a lot more same error .
I had a similar issue with another library which uses ARM NEON too. So if you could help me i will be very thankful

**Comment by mbavaro** [comment]
@h-sh-h have you tried using the default arm distribution obtained with 

sudo apt-get install gcc-arm-linux-gnueabihf
sudo apt-get install g++-arm-linux-gnueabihf

It works for me out of the box...

**Comment by joesavage** [comment]
With respect to those errors in particular, I don't know if I'm missing something here — I feel I must be, because this seems insane — but it looks like Ne10's "fixed size" types like `ne10_int32_t` are actually defined as C's implementation defined size types like `int`. This seems relatively crazy, and may be what you're running up against here. Try changing the typedefs in [NE10_types.h](https://github.com/projectNe10/Ne10/blob/master/inc/NE10_types.h) to use C's real fixed width integer types like `int32_t` and see if that solves your problem.

**Comment by h-sh-h** [comment]
Well thanks to @joesavage, I finally able to get it working.
But there is a note if i compile my code with -std=c99 it gives a lot of errors in lines where asm used but when i use -std=gnu99 it works fine.
If i want to use it with -std=c99 i should replace asm with __asm__ right ?

PS : @mbavaro thanks for your reply. Yes Ne10 compile fine with gnu-linux but i have problem get it working on baremetal ( which there is no OS ). but anyway problem solved thank you !

**Comment by joesavage** [comment]
Awesome. We should really fix those "fixed size" Ne10 types though. Since such a change impacts the whole codebase and would have varying effects in different environments, I'm a little hesitant to make the change myself (without many platforms to test on), but I'll create a new issue for this and hopefully it can get fixed at some point soon.

> if I compile my code with -std=c99 it gives a lot of errors in lines where asm used but when i use -std=gnu99 it works fine.
> If i want to use it with -std=c99 i should replace asm with __ asm __ right ?

Yep, that's right. `asm` will work with `-std=gnu99`, while `__asm__` should be used in its place for compatibility with `-std=c99`.
