### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by jeras** [projectNe10/Ne10#153]
Hi,

We recently started using iPython on a ZYNQ embedded development board. The processing speed of Python itself is not as important as the speed of processing data arrays. Although numpy code is already well optimized, providing a library further optimized for ARM, would be useful.

For now I am just asking if you would accept Python bindings into this repo, and if you have any comments suggestions. Right now I would like to know whether to use master for development or something else. If I get some time I will prepare a pull request (not soon).

**Comment by joesavage** [comment]
Hey, @jeras. That sounds like an interesting use case! I can't say I have any particular comments or suggestions for the moment, but I like the idea of having Ne10 bindings for different languages available. To be honest, I'm not totally sure whether these types of bindings belong in the main repository or not, but I'm happy to think about that more if/when an initial set of bindings is complete.

For the time being I think I'm leaning towards keeping bindings separate from the main C source, but I'd be perfectly happy to link to them in the README file if you want to create an "unofficial" set of bindings. The alternative, of course, would be that we think up an official Python API and thus have some official set of bindings, but considering the lack of resources dedicated to Ne10 at the moment I'm not sure I see that happening any time soon. (Maybe some time in the future, though!)

With respect to what branch you should use for development, I would recommend targeting the master branch as the tagged releases are somewhat out of date (...we should fix that at some point). I don't believe the API has changed since the last tagged release, so this shouldn't introduce any compatibility issues to my knowledge.
