### ISSUE TITLE
PC as target platform

### ISSUE THREAD

**Issue by inetic** [projectNe10/Ne10#59]
Hello, I was wondering if there is a straight forward way to compile Ne10 to work on x86 machines. I understand that neon instructions won't work but I'm guessing the C part should? We have our own minimalist math library (C++ vector and matrix classes) and we thought we could replace some parts entirely with functions from Ne10, rather than keeping our code for x86 and using Ne10 for Arms.

**Comment by Phillip-Wang** [comment]
Hi @ghost, I assume you have ported the math to SSE in assembly. Are you interested in porting them to NEON intrinsic? After that, you can use the NEONvsSSE_6.h you mentioned to port the NEON intrinsic to SSE counterparts.
If you are interested, please refer to [contributing.md](https://github.com/projectNe10/Ne10/blob/master/contributing.md) for contributing.
Also, if you are interested in converting FIR and IIR functions to NEON intrinsic, please don't hesitate to let us know.

**Comment by hdlguy** [comment]
I was able to compile Ne10 for testing my code code on an Intel Linux box before porting to a Xilinx Zynq 64 bit Arm processor.

I am not a professional software developers but I was able to get it to work. I think I created a custom Makefile that compiled just the pure C functions.  Then I modified my code to call those functions because they have different names than the the Neon functions. It was a bit of work.

I imagine this is a fairly common scenario, develop on Linux desktop, deploy on embedded Arm.  It would be nice if this were better supported.  In any case, thanks for a fine library. The fft functions really sped up my code. :-)

I found where I did this work on a fork of Ne10. I hacked some C code, created a Makefile and wrote instructions.  
    https://github.com/hdlguy/Ne10.git
